repos: 
  - repo: local
    hooks:
      - id: check-src-changes
        name: Check for changes in src folder
        entry: bash -c 'git diff --cached --name-only | grep "^src/"'
        language: system
        stages: [commit]
        files: ^src/
        types: [file]