name: CI/CD Pipeline

on: [push, pull_request] 
jobs: # the things being executed
  build:  # the name of your status check
    name: Lint Code Base
    runs-on: ubuntu-latest  # which device on Github's server that you are running the Actions on


    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_HTML: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: .*docs/.*

  test: # the name of your status check, will become important when you do branch protection
    name: Test Code Base
    runs-on: ubuntu-latest # which device on Github's server that you are running the Actions on
    steps:
      - uses: actions/checkout@v4 # using version 4 of Actions
      - name: Install Dependencies
        run: npm install
      - name: Unit Test
        run: npm run test:unit # unit tests
      - name: E2E Test
        run: npm run test:e2e # e2e tests

  generate-docs:
    name: Generate JSDocs
    runs-on: ubuntu-latest # which device on Github's server that you are running the Actions on
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # using version 4 of Actions
      - name: Generate JSDocs
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src
          recurse: true
          output_dir: ./docs
          config_file: jsdoc.json
          front_page: ./docs/backend-documentation.md